//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Blight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlightResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlightResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Blight.BlightResources", typeof(BlightResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber Oil.
        /// </summary>
        public static string AmberOil {
            get {
                return ResourceManager.GetString("AmberOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n20% reduced Cost of Towers.
        /// </summary>
        public static string AmberOilEffect {
            get {
                return ResourceManager.GetString("AmberOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Oil.
        /// </summary>
        public static string AzureOil {
            get {
                return ResourceManager.GetString("AzureOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n15% increased Experience.
        /// </summary>
        public static string AzureOilEffect {
            get {
                return ResourceManager.GetString("AzureOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Oil.
        /// </summary>
        public static string BlackOil {
            get {
                return ResourceManager.GetString("BlackOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n10% chance for Blight Chests to have an\nadditional reward.
        /// </summary>
        public static string BlackOilEffect {
            get {
                return ResourceManager.GetString("BlackOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Oil.
        /// </summary>
        public static string ClearOil {
            get {
                return ResourceManager.GetString("ClearOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n+10% reduced Monster Movement Speed.
        /// </summary>
        public static string ClearOilEffect {
            get {
                return ResourceManager.GetString("ClearOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson Oil.
        /// </summary>
        public static string CrimsonOil {
            get {
                return ResourceManager.GetString("CrimsonOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n3 Blight Chests are Lucky.
        /// </summary>
        public static string CrimsonOilEffect {
            get {
                return ResourceManager.GetString("CrimsonOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden Oil.
        /// </summary>
        public static string GoldenOil {
            get {
                return ResourceManager.GetString("GoldenOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n25% chance for Blight Chests to have an\nadditional Reward.
        /// </summary>
        public static string GoldenOilEffect {
            get {
                return ResourceManager.GetString("GoldenOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opalescent Oil.
        /// </summary>
        public static string OpalescentOil {
            get {
                return ResourceManager.GetString("OpalescentOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +25% Monster Pack Size.
        /// </summary>
        public static string OpalescentOilEffect {
            get {
                return ResourceManager.GetString("OpalescentOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia Oil.
        /// </summary>
        public static string SepiaOil {
            get {
                return ResourceManager.GetString("SepiaOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size
        ///Towers deal 20% more Damage.
        /// </summary>
        public static string SepiaOilEffect {
            get {
                return ResourceManager.GetString("SepiaOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Oil.
        /// </summary>
        public static string SilverOil {
            get {
                return ResourceManager.GetString("SilverOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n5 Blight Chests are Lucky.
        /// </summary>
        public static string SilverOilEffect {
            get {
                return ResourceManager.GetString("SilverOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal Oil.
        /// </summary>
        public static string TealOil {
            get {
                return ResourceManager.GetString("TealOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n2 Blight Chests are Lucky.
        /// </summary>
        public static string TealOilEffect {
            get {
                return ResourceManager.GetString("TealOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdant Oil.
        /// </summary>
        public static string VerdantOil {
            get {
                return ResourceManager.GetString("VerdantOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +15% Monster Pack Size.
        /// </summary>
        public static string VerdantOilEffect {
            get {
                return ResourceManager.GetString("VerdantOilEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet Oil.
        /// </summary>
        public static string VioletOil {
            get {
                return ResourceManager.GetString("VioletOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +5% Monster Pack Size\n30% increased Quantity of Items.
        /// </summary>
        public static string VioletOilEffect {
            get {
                return ResourceManager.GetString("VioletOilEffect", resourceCulture);
            }
        }
    }
}
