//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Betrayal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BetrayalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BetrayalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Betrayal.BetrayalResources", typeof(BetrayalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled
        ///Armor.
        /// </summary>
        public static string AislingFortification {
            get {
                return ResourceManager.GetString("AislingFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled
        ///Jewellery.
        /// </summary>
        public static string AislingIntervention {
            get {
                return ResourceManager.GetString("AislingIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisling.
        /// </summary>
        public static string AislingName {
            get {
                return ResourceManager.GetString("AislingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Veiled
        ///Mod(s).
        /// </summary>
        public static string AislingResearch {
            get {
                return ResourceManager.GetString("AislingResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 Mod
        ///Level2: Low Chance for 2 Mods
        ///Level3: 2 Mods.
        /// </summary>
        public static string AislingResearchTooltip {
            get {
                return ResourceManager.GetString("AislingResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled
        ///Weapons.
        /// </summary>
        public static string AislingTransportaion {
            get {
                return ResourceManager.GetString("AislingTransportaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger
        ///Orbs.
        /// </summary>
        public static string CameriaFortification {
            get {
                return ResourceManager.GetString("CameriaFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphite
        ///Scarab.
        /// </summary>
        public static string CameriaIntervention {
            get {
                return ResourceManager.GetString("CameriaIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameria.
        /// </summary>
        public static string CameriaName {
            get {
                return ResourceManager.GetString("CameriaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sextants.
        /// </summary>
        public static string CameriaResearch {
            get {
                return ResourceManager.GetString("CameriaResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeworn
        ///Relics.
        /// </summary>
        public static string CameriaTransportation {
            get {
                return ResourceManager.GetString("CameriaTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Specific Items
        ///(Headhunter possible).
        /// </summary>
        public static string CameriaTransportationTooltip {
            get {
                return ResourceManager.GetString("CameriaTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique
        ///Armor.
        /// </summary>
        public static string ElreonFortification {
            get {
                return ResourceManager.GetString("ElreonFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliquary
        ///Scarabs.
        /// </summary>
        public static string ElreonIntervention {
            get {
                return ResourceManager.GetString("ElreonIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elreon.
        /// </summary>
        public static string ElreonName {
            get {
                return ResourceManager.GetString("ElreonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique
        ///Jewellery.
        /// </summary>
        public static string ElreonResearch {
            get {
                return ResourceManager.GetString("ElreonResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique
        ///Weapons.
        /// </summary>
        public static string ElreonTransportation {
            get {
                return ResourceManager.GetString("ElreonTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random
        ///Div Cards.
        /// </summary>
        public static string GraviciusFortification {
            get {
                return ResourceManager.GetString("GraviciusFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card
        ///Scarab.
        /// </summary>
        public static string GraviciusIntervention {
            get {
                return ResourceManager.GetString("GraviciusIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravicius.
        /// </summary>
        public static string GraviciusName {
            get {
                return ResourceManager.GetString("GraviciusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap
        ///Div Cards.
        /// </summary>
        public static string GraviciusResearch {
            get {
                return ResourceManager.GetString("GraviciusResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card
        ///Stack.
        /// </summary>
        public static string GraviciusTransportation {
            get {
                return ResourceManager.GetString("GraviciusTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence
        ///Crafting.
        /// </summary>
        public static string GuffFortification {
            get {
                return ResourceManager.GetString("GuffFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Scouring
        ///5 * 4 Essences
        ///20 Exalted
        ///1 Vaal
        ///Level1: 8 Seconds
        ///Level2: 12 Seconds
        ///Level3: 18 Seconds.
        /// </summary>
        public static string GuffFortificationTooltip {
            get {
                return ResourceManager.GetString("GuffFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteration
        ///Crafting.
        /// </summary>
        public static string GuffIntervention {
            get {
                return ResourceManager.GetString("GuffIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Transmutation
        ///200 Alteration
        ///100 AUgmentation
        ///1 Regal
        ///1 Exalted
        ///1 Divine
        ///1 Vaal
        ///Level1: 8 Seconds
        ///Level2: 12 Seconds
        ///Level3: 18 Seconds.
        /// </summary>
        public static string GuffInterventionTooltip {
            get {
                return ResourceManager.GetString("GuffInterventionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guff.
        /// </summary>
        public static string GuffName {
            get {
                return ResourceManager.GetString("GuffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annull\\Ex
        ///Crafting.
        /// </summary>
        public static string GuffResearch {
            get {
                return ResourceManager.GetString("GuffResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch
        ///100 Anullment
        ///100 Exalted
        ///1 Divine
        ///1 Blessed
        ///1 Vaal
        ///Level1: 8 Seconds
        ///Level2: 12 Seconds
        ///Level3: 18 Seconds.
        /// </summary>
        public static string GuffResearchTooltip {
            get {
                return ResourceManager.GetString("GuffResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos
        ///Crafting.
        /// </summary>
        public static string GuffTransportation {
            get {
                return ResourceManager.GetString("GuffTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch
        ///200 Chaos
        ///6 Exalted
        ///20 Divine
        ///20 Blessed
        ///1 Vaal
        ///Level1: 8 Seconds
        ///Level2: 12 Seconds
        ///Level3: 18 Seconds.
        /// </summary>
        public static string GuffTransportationTooltip {
            get {
                return ResourceManager.GetString("GuffTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongboxes.
        /// </summary>
        public static string HakuFortification {
            get {
                return ResourceManager.GetString("HakuFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongbox
        ///Scarab.
        /// </summary>
        public static string HakuIntervention {
            get {
                return ResourceManager.GetString("HakuIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haku.
        /// </summary>
        public static string HakuName {
            get {
                return ResourceManager.GetString("HakuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality
        ///Items.
        /// </summary>
        public static string HakuResearch {
            get {
                return ResourceManager.GetString("HakuResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Items.
        /// </summary>
        public static string HakuTransportation {
            get {
                return ResourceManager.GetString("HakuTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor
        ///Quality.
        /// </summary>
        public static string HillockFortification {
            get {
                return ResourceManager.GetString("HillockFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %
        ///Level2: 26 %
        ///Level3: 28 %.
        /// </summary>
        public static string HillockFortificationTooltip {
            get {
                return ResourceManager.GetString("HillockFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map
        ///Quality.
        /// </summary>
        public static string HillockIntervention {
            get {
                return ResourceManager.GetString("HillockIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 25 %
        ///Level2: 30 %
        ///Level3: 35 %.
        /// </summary>
        public static string HillockInterventionTooltip {
            get {
                return ResourceManager.GetString("HillockInterventionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hillock.
        /// </summary>
        public static string HillockName {
            get {
                return ResourceManager.GetString("HillockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask
        ///Quality.
        /// </summary>
        public static string HillockResearch {
            get {
                return ResourceManager.GetString("HillockResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 22 %
        ///Level2: 24 %
        ///Level3: 26%.
        /// </summary>
        public static string HillockResearchTooltip {
            get {
                return ResourceManager.GetString("HillockResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon
        ///Quality.
        /// </summary>
        public static string HillockTransportation {
            get {
                return ResourceManager.GetString("HillockTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %
        ///Level2: 26 %
        ///Level3: 28%.
        /// </summary>
        public static string HillockTransportationTooltip {
            get {
                return ResourceManager.GetString("HillockTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss
        ///Jewels.
        /// </summary>
        public static string ItThatFledFortification {
            get {
                return ResourceManager.GetString("ItThatFledFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach
        ///Scarab.
        /// </summary>
        public static string ItThatFledIntervention {
            get {
                return ResourceManager.GetString("ItThatFledIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItThatFled.
        /// </summary>
        public static string ItThatFledName {
            get {
                return ResourceManager.GetString("ItThatFledName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade
        ///Breachstone.
        /// </summary>
        public static string ItThatFledResearch {
            get {
                return ResourceManager.GetString("ItThatFledResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Charged
        ///Level2: Enriched
        ///Level3: Pure.
        /// </summary>
        public static string ItThatFledResearchTooltip {
            get {
                return ResourceManager.GetString("ItThatFledResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach
        ///Splinter.
        /// </summary>
        public static string ItThatFledTransportation {
            get {
                return ResourceManager.GetString("ItThatFledTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency
        ///Shards.
        /// </summary>
        public static string JanusFortification {
            get {
                return ResourceManager.GetString("JanusFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus
        ///Scarab.
        /// </summary>
        public static string JanusIntervention {
            get {
                return ResourceManager.GetString("JanusIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janus.
        /// </summary>
        public static string JanusName {
            get {
                return ResourceManager.GetString("JanusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus
        ///Coins.
        /// </summary>
        public static string JanusResearch {
            get {
                return ResourceManager.GetString("JanusResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality
        ///Currency.
        /// </summary>
        public static string JanusTransportaion {
            get {
                return ResourceManager.GetString("JanusTransportaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary
        ///Items.
        /// </summary>
        public static string JorginFortification {
            get {
                return ResourceManager.GetString("JorginFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary
        ///Scarab.
        /// </summary>
        public static string JorginIntervention {
            get {
                return ResourceManager.GetString("JorginIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jorgin.
        /// </summary>
        public static string JorginName {
            get {
                return ResourceManager.GetString("JorginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet to
        ///Talisman.
        /// </summary>
        public static string JorginResearch {
            get {
                return ResourceManager.GetString("JorginResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Level 1 Talisman
        ///Level2: Level 2 Talisman
        ///Level3: Level 3 Talisman.
        /// </summary>
        public static string JorginResearchTooltip {
            get {
                return ResourceManager.GetString("JorginResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talismans.
        /// </summary>
        public static string JorginTransportation {
            get {
                return ResourceManager.GetString("JorginTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map
        ///Fragments.
        /// </summary>
        public static string KorellFortification {
            get {
                return ResourceManager.GetString("KorellFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder
        ///Scarab.
        /// </summary>
        public static string KorellIntervention {
            get {
                return ResourceManager.GetString("KorellIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korell.
        /// </summary>
        public static string KorellName {
            get {
                return ResourceManager.GetString("KorellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossils.
        /// </summary>
        public static string KorellResearch {
            get {
                return ResourceManager.GetString("KorellResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essences.
        /// </summary>
        public static string KorellTransportation {
            get {
                return ResourceManager.GetString("KorellTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random
        ///Currency.
        /// </summary>
        public static string LeoFortification {
            get {
                return ResourceManager.GetString("LeoFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torment
        ///Scarab.
        /// </summary>
        public static string LeoIntervention {
            get {
                return ResourceManager.GetString("LeoIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string LeoName {
            get {
                return ResourceManager.GetString("LeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency
        ///Use.
        /// </summary>
        public static string LeoResearch {
            get {
                return ResourceManager.GetString("LeoResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Blessed Orb
        ///Level2: Divine Orb
        ///Level3: Exalted Orb.
        /// </summary>
        public static string LeoResearchTooltip {
            get {
                return ResourceManager.GetString("LeoResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver
        ///Coins.
        /// </summary>
        public static string LeoTransportation {
            get {
                return ResourceManager.GetString("LeoTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One
        ///Unique.
        /// </summary>
        public static string RikerFortification {
            get {
                return ResourceManager.GetString("RikerFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take On
        ///Div Card.
        /// </summary>
        public static string RikerIntervention {
            get {
                return ResourceManager.GetString("RikerIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riker.
        /// </summary>
        public static string RikerName {
            get {
                return ResourceManager.GetString("RikerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One
        ///Veiled.
        /// </summary>
        public static string RikerResearch {
            get {
                return ResourceManager.GetString("RikerResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One
        ///Currency.
        /// </summary>
        public static string RikerTransportation {
            get {
                return ResourceManager.GetString("RikerTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Maps.
        /// </summary>
        public static string RinFortification {
            get {
                return ResourceManager.GetString("RinFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartography
        ///Scarab.
        /// </summary>
        public static string RinIntervention {
            get {
                return ResourceManager.GetString("RinIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rin.
        /// </summary>
        public static string RinName {
            get {
                return ResourceManager.GetString("RinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique
        ///Maps.
        /// </summary>
        public static string RinResearch {
            get {
                return ResourceManager.GetString("RinResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Maps.
        /// </summary>
        public static string RinTransportation {
            get {
                return ResourceManager.GetString("RinTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted
        ///Items.
        /// </summary>
        public static string ToraFortification {
            get {
                return ResourceManager.GetString("ToraFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Gloves
        ///Level2: Boots
        ///Level3: Helmet.
        /// </summary>
        public static string ToraFortificationTooltip {
            get {
                return ResourceManager.GetString("ToraFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger
        ///Scarab.
        /// </summary>
        public static string ToraIntervention {
            get {
                return ResourceManager.GetString("ToraIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tora.
        /// </summary>
        public static string ToraName {
            get {
                return ResourceManager.GetString("ToraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem
        ///Experience.
        /// </summary>
        public static string ToraResearch {
            get {
                return ResourceManager.GetString("ToraResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 20m Exp
        ///Level2: 70m Exp
        ///Level3: 200m Exp.
        /// </summary>
        public static string ToraResearchTooltip {
            get {
                return ResourceManager.GetString("ToraResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Item
        ///[Timed].
        /// </summary>
        public static string ToraTransportation {
            get {
                return ResourceManager.GetString("ToraTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Limit: 8 Seconds
        ///Currency
        ///Divination Cards
        ///Uniques
        ///Item Level 100 Rare.
        /// </summary>
        public static string ToraTransportationTooltip {
            get {
                return ResourceManager.GetString("ToraTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string TypeFortification {
            get {
                return ResourceManager.GetString("TypeFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        public static string TypeIntervention {
            get {
                return ResourceManager.GetString("TypeIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string TypeResearch {
            get {
                return ResourceManager.GetString("TypeResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TypeTransportation {
            get {
                return ResourceManager.GetString("TypeTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Armor.
        /// </summary>
        public static string VaganFortification {
            get {
                return ResourceManager.GetString("VaganFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Jewels.
        /// </summary>
        public static string VaganIntervention {
            get {
                return ResourceManager.GetString("VaganIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vagan.
        /// </summary>
        public static string VaganName {
            get {
                return ResourceManager.GetString("VaganName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Jewellery.
        /// </summary>
        public static string VaganResearch {
            get {
                return ResourceManager.GetString("VaganResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare
        ///Weapons.
        /// </summary>
        public static string VaganTransportation {
            get {
                return ResourceManager.GetString("VaganTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 White Socket
        ///Level2: 1-2 White Sockets
        ///Level3: 1-3 White Sockets.
        /// </summary>
        public static string VoriceResearchTooltip {
            get {
                return ResourceManager.GetString("VoriceResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking
        ///Currency.
        /// </summary>
        public static string VoriciFortification {
            get {
                return ResourceManager.GetString("VoriciFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaper
        ///Scarab.
        /// </summary>
        public static string VoriciIntervention {
            get {
                return ResourceManager.GetString("VoriciIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorici.
        /// </summary>
        public static string VoriciName {
            get {
                return ResourceManager.GetString("VoriciName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White
        ///Socktes.
        /// </summary>
        public static string VoriciResearch {
            get {
                return ResourceManager.GetString("VoriciResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality
        ///Gems.
        /// </summary>
        public static string VoriciTransportation {
            get {
                return ResourceManager.GetString("VoriciTransportation", resourceCulture);
            }
        }
    }
}
