//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Betrayal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BetrayalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BetrayalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Betrayal.BetrayalResources", typeof(BetrayalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nArmor.
        /// </summary>
        public static string AislingFortification {
            get {
                return ResourceManager.GetString("AislingFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nJewellery.
        /// </summary>
        public static string AislingIntervention {
            get {
                return ResourceManager.GetString("AislingIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Veiled\nMod(s).
        /// </summary>
        public static string AislingResearch {
            get {
                return ResourceManager.GetString("AislingResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 Mod\nLevel2: Low Chance for 2 Mods\nLevel3: 2 Mods.
        /// </summary>
        public static string AislingResearchTooltip {
            get {
                return ResourceManager.GetString("AislingResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiled\nWeapons.
        /// </summary>
        public static string AislingTransportaion {
            get {
                return ResourceManager.GetString("AislingTransportaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger\nOrbs.
        /// </summary>
        public static string CameriaFortification {
            get {
                return ResourceManager.GetString("CameriaFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulphite\nScarab.
        /// </summary>
        public static string CameriaIntervention {
            get {
                return ResourceManager.GetString("CameriaIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sextants.
        /// </summary>
        public static string CameriaResearch {
            get {
                return ResourceManager.GetString("CameriaResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeworn\nRelics.
        /// </summary>
        public static string CameriaTransportation {
            get {
                return ResourceManager.GetString("CameriaTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Specific Items\n(Headhunter possible).
        /// </summary>
        public static string CameriaTransportationTooltip {
            get {
                return ResourceManager.GetString("CameriaTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nArmor.
        /// </summary>
        public static string ElreonFortification {
            get {
                return ResourceManager.GetString("ElreonFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliquary\nScarabs.
        /// </summary>
        public static string ElreonIntervention {
            get {
                return ResourceManager.GetString("ElreonIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nJewellery.
        /// </summary>
        public static string ElreonResearch {
            get {
                return ResourceManager.GetString("ElreonResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nWeapons.
        /// </summary>
        public static string ElreonTransportation {
            get {
                return ResourceManager.GetString("ElreonTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random\nDiv Cards.
        /// </summary>
        public static string GraviciusFortification {
            get {
                return ResourceManager.GetString("GraviciusFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card\nScarab.
        /// </summary>
        public static string GraviciusIntervention {
            get {
                return ResourceManager.GetString("GraviciusIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap\nDiv Cards.
        /// </summary>
        public static string GraviciusResearch {
            get {
                return ResourceManager.GetString("GraviciusResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div Card\nStack.
        /// </summary>
        public static string GraviciusTransportation {
            get {
                return ResourceManager.GetString("GraviciusTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence\nCrafting.
        /// </summary>
        public static string GuffFortification {
            get {
                return ResourceManager.GetString("GuffFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Scouring\n5 * 4 Essences\n20 Exalted\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        public static string GuffFortificationTooltip {
            get {
                return ResourceManager.GetString("GuffFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteration\nCrafting.
        /// </summary>
        public static string GuffIntervention {
            get {
                return ResourceManager.GetString("GuffIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Transmutation\n200 Alteration\n100 AUgmentation\n1 Regal\n1 Exalted\n1 Divine\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        public static string GuffInterventionTooltip {
            get {
                return ResourceManager.GetString("GuffInterventionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annull\\Ex\nCrafting.
        /// </summary>
        public static string GuffResearch {
            get {
                return ResourceManager.GetString("GuffResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch\n100 Anullment\n100 Exalted\n1 Divine\n1 Blessed\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        public static string GuffResearchTooltip {
            get {
                return ResourceManager.GetString("GuffResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos\nCrafting.
        /// </summary>
        public static string GuffTransportation {
            get {
                return ResourceManager.GetString("GuffTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Alch\n200 Chaos\n6 Exalted\n20 Divine\n20 Blessed\n1 Vaal\nLevel1: 8 Seconds\nLevel2: 12 Seconds\nLevel3: 18 Seconds.
        /// </summary>
        public static string GuffTransportationTooltip {
            get {
                return ResourceManager.GetString("GuffTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongboxes.
        /// </summary>
        public static string HakuFortification {
            get {
                return ResourceManager.GetString("HakuFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongbox\nScarab.
        /// </summary>
        public static string HakuIntervention {
            get {
                return ResourceManager.GetString("HakuIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nItems.
        /// </summary>
        public static string HakuResearch {
            get {
                return ResourceManager.GetString("HakuResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nItems.
        /// </summary>
        public static string HakuTransportation {
            get {
                return ResourceManager.GetString("HakuTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor\nQuality.
        /// </summary>
        public static string HillockFortification {
            get {
                return ResourceManager.GetString("HillockFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %\nLevel2: 26 %\nLevel3: 28 %.
        /// </summary>
        public static string HillockFortificationTooltip {
            get {
                return ResourceManager.GetString("HillockFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map\nQuality.
        /// </summary>
        public static string HillockIntervention {
            get {
                return ResourceManager.GetString("HillockIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 25 %\nLevel2: 30 %\nLevel3: 35 %.
        /// </summary>
        public static string HillockInterventionTooltip {
            get {
                return ResourceManager.GetString("HillockInterventionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask\nQuality.
        /// </summary>
        public static string HillockResearch {
            get {
                return ResourceManager.GetString("HillockResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 22 %\nLevel2: 24 %\nLevel3: 26%.
        /// </summary>
        public static string HillockResearchTooltip {
            get {
                return ResourceManager.GetString("HillockResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon\nQuality.
        /// </summary>
        public static string HillockTransportation {
            get {
                return ResourceManager.GetString("HillockTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 24 %\nLevel2: 26 %\nLevel3: 28%.
        /// </summary>
        public static string HillockTransportationTooltip {
            get {
                return ResourceManager.GetString("HillockTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss\nJewels.
        /// </summary>
        public static string ItThatFledFortification {
            get {
                return ResourceManager.GetString("ItThatFledFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach\nScarab.
        /// </summary>
        public static string ItThatFledIntervention {
            get {
                return ResourceManager.GetString("ItThatFledIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade\nBreachstone.
        /// </summary>
        public static string ItThatFledResearch {
            get {
                return ResourceManager.GetString("ItThatFledResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Charged\nLevel2: Enriched\nLevel3: Pure.
        /// </summary>
        public static string ItThatFledResearchTooltip {
            get {
                return ResourceManager.GetString("ItThatFledResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach\nSplinter.
        /// </summary>
        public static string ItThatFledTransportation {
            get {
                return ResourceManager.GetString("ItThatFledTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency\nShards.
        /// </summary>
        public static string JanusFortification {
            get {
                return ResourceManager.GetString("JanusFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus\nScarab.
        /// </summary>
        public static string JanusIntervention {
            get {
                return ResourceManager.GetString("JanusIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perandus\nCoins.
        /// </summary>
        public static string JanusResearch {
            get {
                return ResourceManager.GetString("JanusResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nCurrency.
        /// </summary>
        public static string JanusTransportaion {
            get {
                return ResourceManager.GetString("JanusTransportaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary\nItems.
        /// </summary>
        public static string JorginFortification {
            get {
                return ResourceManager.GetString("JorginFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary\nScarab.
        /// </summary>
        public static string JorginIntervention {
            get {
                return ResourceManager.GetString("JorginIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet to\nTalisman.
        /// </summary>
        public static string JorginResearch {
            get {
                return ResourceManager.GetString("JorginResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Level 1 Talisman\nLevel2: Level 2 Talisman\nLevel3: Level 3 Talisman.
        /// </summary>
        public static string JorginResearchTooltip {
            get {
                return ResourceManager.GetString("JorginResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talismans.
        /// </summary>
        public static string JorginTransportation {
            get {
                return ResourceManager.GetString("JorginTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map\nFragments.
        /// </summary>
        public static string KorrelFortification {
            get {
                return ResourceManager.GetString("KorrelFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elder\nScarab.
        /// </summary>
        public static string KorrelIntervention {
            get {
                return ResourceManager.GetString("KorrelIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossils.
        /// </summary>
        public static string KorrellResearch {
            get {
                return ResourceManager.GetString("KorrellResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essences.
        /// </summary>
        public static string KorrellTransportation {
            get {
                return ResourceManager.GetString("KorrellTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random\nCurrency.
        /// </summary>
        public static string LeoFortification {
            get {
                return ResourceManager.GetString("LeoFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torment\nScarab.
        /// </summary>
        public static string LeoIntervention {
            get {
                return ResourceManager.GetString("LeoIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency\nUse.
        /// </summary>
        public static string LeoResearch {
            get {
                return ResourceManager.GetString("LeoResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Blessed Orb\nLevel2: Divine Orb\nLevel3: Exalted Orb.
        /// </summary>
        public static string LeoResearchTooltip {
            get {
                return ResourceManager.GetString("LeoResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver\nCoins.
        /// </summary>
        public static string LeoTransportation {
            get {
                return ResourceManager.GetString("LeoTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nUnique.
        /// </summary>
        public static string RikerFortification {
            get {
                return ResourceManager.GetString("RikerFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take On\nDiv Card.
        /// </summary>
        public static string RikerIntervention {
            get {
                return ResourceManager.GetString("RikerIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nVeiled.
        /// </summary>
        public static string RikerResearch {
            get {
                return ResourceManager.GetString("RikerResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take One\nCurrency.
        /// </summary>
        public static string RikerTransportation {
            get {
                return ResourceManager.GetString("RikerTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nMaps.
        /// </summary>
        public static string RinFortification {
            get {
                return ResourceManager.GetString("RinFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartography\nScarab.
        /// </summary>
        public static string RinIntervention {
            get {
                return ResourceManager.GetString("RinIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique\nMaps.
        /// </summary>
        public static string RinResearch {
            get {
                return ResourceManager.GetString("RinResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal\nMaps.
        /// </summary>
        public static string RinTransportation {
            get {
                return ResourceManager.GetString("RinTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted\nItems.
        /// </summary>
        public static string ToraFortification {
            get {
                return ResourceManager.GetString("ToraFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: Gloves\nLevel2: Boots\nLevel3: Helmet.
        /// </summary>
        public static string ToraFortificationTooltip {
            get {
                return ResourceManager.GetString("ToraFortificationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbinger\nScarab.
        /// </summary>
        public static string ToraIntervention {
            get {
                return ResourceManager.GetString("ToraIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem\nExperience.
        /// </summary>
        public static string ToraResearch {
            get {
                return ResourceManager.GetString("ToraResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 20m Exp\nLevel2: 70m Exp\nLevel3: 200m Exp.
        /// </summary>
        public static string ToraResearchTooltip {
            get {
                return ResourceManager.GetString("ToraResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Item\n[Timed].
        /// </summary>
        public static string ToraTransportation {
            get {
                return ResourceManager.GetString("ToraTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Limit: 8 Seconds\nCurrency\nDivination Cards\nUniques\nItem Level 100 Rare.
        /// </summary>
        public static string ToraTransportationTooltip {
            get {
                return ResourceManager.GetString("ToraTransportationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nArmor.
        /// </summary>
        public static string VaganFortification {
            get {
                return ResourceManager.GetString("VaganFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nJewels.
        /// </summary>
        public static string VaganIntervention {
            get {
                return ResourceManager.GetString("VaganIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nJewellery.
        /// </summary>
        public static string VaganResearch {
            get {
                return ResourceManager.GetString("VaganResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare\nWeapons.
        /// </summary>
        public static string VaganTransportation {
            get {
                return ResourceManager.GetString("VaganTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1: 1 White Socket\nLevel2: 1-2 White Sockets\nLevel3: 1-3 White Sockets.
        /// </summary>
        public static string VoriceResearchTooltip {
            get {
                return ResourceManager.GetString("VoriceResearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking\nCurrency.
        /// </summary>
        public static string VoriciFortification {
            get {
                return ResourceManager.GetString("VoriciFortification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaper\nScarab.
        /// </summary>
        public static string VoriciIntervention {
            get {
                return ResourceManager.GetString("VoriciIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White\nSocktes.
        /// </summary>
        public static string VoriciResearch {
            get {
                return ResourceManager.GetString("VoriciResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality\nGems.
        /// </summary>
        public static string VoriciTransportation {
            get {
                return ResourceManager.GetString("VoriciTransportation", resourceCulture);
            }
        }
    }
}
