//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Presentation.Localization.Prices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PriceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Presentation.Localization.Prices.PriceResources", typeof(PriceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string Age_Day {
            get {
                return ResourceManager.GetString("Age_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string Age_Days {
            get {
                return ResourceManager.GetString("Age_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string Age_Hour {
            get {
                return ResourceManager.GetString("Age_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string Age_Hours {
            get {
                return ResourceManager.GetString("Age_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string Age_Minute {
            get {
                return ResourceManager.GetString("Age_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string Age_Minutes {
            get {
                return ResourceManager.GetString("Age_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Age_Now {
            get {
                return ResourceManager.GetString("Age_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string Age_Seconds {
            get {
                return ResourceManager.GetString("Age_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Accessory.
        /// </summary>
        public static string Class_Accessory {
            get {
                return ResourceManager.GetString("Class_Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        public static string Class_AccessoryAmulet {
            get {
                return ResourceManager.GetString("Class_AccessoryAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt.
        /// </summary>
        public static string Class_AccessoryBelt {
            get {
                return ResourceManager.GetString("Class_AccessoryBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        public static string Class_AccessoryRing {
            get {
                return ResourceManager.GetString("Class_AccessoryRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Class_Any {
            get {
                return ResourceManager.GetString("Class_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Armour.
        /// </summary>
        public static string Class_Armour {
            get {
                return ResourceManager.GetString("Class_Armour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        public static string Class_ArmourBoots {
            get {
                return ResourceManager.GetString("Class_ArmourBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Armour.
        /// </summary>
        public static string Class_ArmourChest {
            get {
                return ResourceManager.GetString("Class_ArmourChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        public static string Class_ArmourGloves {
            get {
                return ResourceManager.GetString("Class_ArmourGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmet.
        /// </summary>
        public static string Class_ArmourHelmet {
            get {
                return ResourceManager.GetString("Class_ArmourHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiver.
        /// </summary>
        public static string Class_ArmourQuiver {
            get {
                return ResourceManager.GetString("Class_ArmourQuiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Class_ArmourShield {
            get {
                return ResourceManager.GetString("Class_ArmourShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Class_Card {
            get {
                return ResourceManager.GetString("Class_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Currency.
        /// </summary>
        public static string Class_Currency {
            get {
                return ResourceManager.GetString("Class_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossil.
        /// </summary>
        public static string Class_CurrencyFossil {
            get {
                return ResourceManager.GetString("Class_CurrencyFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incubator.
        /// </summary>
        public static string Class_CurrencyIncubator {
            get {
                return ResourceManager.GetString("Class_CurrencyIncubator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Fragment.
        /// </summary>
        public static string Class_CurrencyPiece {
            get {
                return ResourceManager.GetString("Class_CurrencyPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resonator.
        /// </summary>
        public static string Class_CurrencyResonator {
            get {
                return ResourceManager.GetString("Class_CurrencyResonator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask.
        /// </summary>
        public static string Class_Flask {
            get {
                return ResourceManager.GetString("Class_Flask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Gem.
        /// </summary>
        public static string Class_Gem {
            get {
                return ResourceManager.GetString("Class_Gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Gem.
        /// </summary>
        public static string Class_GemActive {
            get {
                return ResourceManager.GetString("Class_GemActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awakened Support Gem.
        /// </summary>
        public static string Class_GemAwakenedSupport {
            get {
                return ResourceManager.GetString("Class_GemAwakenedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Gem.
        /// </summary>
        public static string Class_GemSupport {
            get {
                return ResourceManager.GetString("Class_GemSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Jewel.
        /// </summary>
        public static string Class_Jewel {
            get {
                return ResourceManager.GetString("Class_Jewel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyss Jewel.
        /// </summary>
        public static string Class_JewelAbyss {
            get {
                return ResourceManager.GetString("Class_JewelAbyss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Jewel.
        /// </summary>
        public static string Class_JewelBase {
            get {
                return ResourceManager.GetString("Class_JewelBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Jewel.
        /// </summary>
        public static string Class_JewelCluster {
            get {
                return ResourceManager.GetString("Class_JewelCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaguestone.
        /// </summary>
        public static string Class_Leaguestone {
            get {
                return ResourceManager.GetString("Class_Leaguestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Class_Map {
            get {
                return ResourceManager.GetString("Class_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Fragment.
        /// </summary>
        public static string Class_MapFragment {
            get {
                return ResourceManager.GetString("Class_MapFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarab.
        /// </summary>
        public static string Class_MapScarab {
            get {
                return ResourceManager.GetString("Class_MapScarab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured Beast.
        /// </summary>
        public static string Class_MonsterBeast {
            get {
                return ResourceManager.GetString("Class_MonsterBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorph Sample.
        /// </summary>
        public static string Class_MonsterSample {
            get {
                return ResourceManager.GetString("Class_MonsterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prophecy.
        /// </summary>
        public static string Class_Prophecy {
            get {
                return ResourceManager.GetString("Class_Prophecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchstone.
        /// </summary>
        public static string Class_Watchstone {
            get {
                return ResourceManager.GetString("Class_Watchstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Weapon.
        /// </summary>
        public static string Class_Weapon {
            get {
                return ResourceManager.GetString("Class_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        public static string Class_WeaponBow {
            get {
                return ResourceManager.GetString("Class_WeaponBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claw.
        /// </summary>
        public static string Class_WeaponClaw {
            get {
                return ResourceManager.GetString("Class_WeaponClaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Dagger.
        /// </summary>
        public static string Class_WeaponDagger {
            get {
                return ResourceManager.GetString("Class_WeaponDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Weapon.
        /// </summary>
        public static string Class_WeaponOne {
            get {
                return ResourceManager.GetString("Class_WeaponOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Axe.
        /// </summary>
        public static string Class_WeaponOneAxe {
            get {
                return ResourceManager.GetString("Class_WeaponOneAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Mace.
        /// </summary>
        public static string Class_WeaponOneMace {
            get {
                return ResourceManager.GetString("Class_WeaponOneMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Melee Weapon.
        /// </summary>
        public static string Class_WeaponOneMelee {
            get {
                return ResourceManager.GetString("Class_WeaponOneMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Handed Sword.
        /// </summary>
        public static string Class_WeaponOneSword {
            get {
                return ResourceManager.GetString("Class_WeaponOneSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Rod.
        /// </summary>
        public static string Class_WeaponRod {
            get {
                return ResourceManager.GetString("Class_WeaponRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune Dagger.
        /// </summary>
        public static string Class_WeaponRuneDagger {
            get {
                return ResourceManager.GetString("Class_WeaponRuneDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sceptre.
        /// </summary>
        public static string Class_WeaponSceptre {
            get {
                return ResourceManager.GetString("Class_WeaponSceptre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Staff.
        /// </summary>
        public static string Class_WeaponStaff {
            get {
                return ResourceManager.GetString("Class_WeaponStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed Axe.
        /// </summary>
        public static string Class_WeaponTwoAxe {
            get {
                return ResourceManager.GetString("Class_WeaponTwoAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed Mace.
        /// </summary>
        public static string Class_WeaponTwoMace {
            get {
                return ResourceManager.GetString("Class_WeaponTwoMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed Melee Weapon.
        /// </summary>
        public static string Class_WeaponTwoMelee {
            get {
                return ResourceManager.GetString("Class_WeaponTwoMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Handed Sword.
        /// </summary>
        public static string Class_WeaponTwoSword {
            get {
                return ResourceManager.GetString("Class_WeaponTwoSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand.
        /// </summary>
        public static string Class_WeaponWand {
            get {
                return ResourceManager.GetString("Class_WeaponWand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warstaff.
        /// </summary>
        public static string Class_WeaponWarstaff {
            get {
                return ResourceManager.GetString("Class_WeaponWarstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted.
        /// </summary>
        public static string Corrupted {
            get {
                return ResourceManager.GetString("Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} out of {1} items.
        /// </summary>
        public static string CountString {
            get {
                return ResourceManager.GetString("CountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage per second.
        /// </summary>
        public static string Filters_Dps {
            get {
                return ResourceManager.GetString("Filters_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental DPS.
        /// </summary>
        public static string Filters_EDps {
            get {
                return ResourceManager.GetString("Filters_EDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Filters_Max {
            get {
                return ResourceManager.GetString("Filters_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Filters_Min {
            get {
                return ResourceManager.GetString("Filters_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPS.
        /// </summary>
        public static string Filters_PDps {
            get {
                return ResourceManager.GetString("Filters_PDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        public static string ItemLevel {
            get {
                return ResourceManager.GetString("ItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More Data.
        /// </summary>
        public static string LoadMoreData {
            get {
                return ResourceManager.GetString("LoadMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour at max Quality.
        /// </summary>
        public static string MaxQualityArmour {
            get {
                return ResourceManager.GetString("MaxQualityArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS at max Quality.
        /// </summary>
        public static string MaxQualityDps {
            get {
                return ResourceManager.GetString("MaxQualityDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental DPS at max Quality.
        /// </summary>
        public static string MaxQualityEDps {
            get {
                return ResourceManager.GetString("MaxQualityEDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Shield at max Quality.
        /// </summary>
        public static string MaxQualityEnergyShield {
            get {
                return ResourceManager.GetString("MaxQualityEnergyShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion at max Quality.
        /// </summary>
        public static string MaxQualityEvasion {
            get {
                return ResourceManager.GetString("MaxQualityEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPS at max Quality.
        /// </summary>
        public static string MaxQualityPDps {
            get {
                return ResourceManager.GetString("MaxQualityPDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string OverlayAccountName {
            get {
                return ResourceManager.GetString("OverlayAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string OverlayAge {
            get {
                return ResourceManager.GetString("OverlayAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string OverlayCharacter {
            get {
                return ResourceManager.GetString("OverlayCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl.
        /// </summary>
        public static string OverlayItemLevel {
            get {
                return ResourceManager.GetString("OverlayItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string OverlayPrice {
            get {
                return ResourceManager.GetString("OverlayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poe.Ninja: {0}c - Last updated: {1}.
        /// </summary>
        public static string PoeNinjaString {
            get {
                return ResourceManager.GetString("PoeNinjaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction: {0} - Confidence: {1}%.
        /// </summary>
        public static string PredictionString {
            get {
                return ResourceManager.GetString("PredictionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires.
        /// </summary>
        public static string Requires {
            get {
                return ResourceManager.GetString("Requires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified.
        /// </summary>
        public static string Unidentified {
            get {
                return ResourceManager.GetString("Unidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        public static string UpdateSeconds {
            get {
                return ResourceManager.GetString("UpdateSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating shortly.
        /// </summary>
        public static string UpdateShortly {
            get {
                return ResourceManager.GetString("UpdateShortly", resourceCulture);
            }
        }
    }
}
