//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Incursion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncursionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncursionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Incursion.IncursionResources", typeof(IncursionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex of Ascension.
        /// </summary>
        public static string ApexOfAscension {
            get {
                return ResourceManager.GetString("ApexOfAscension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena of Valour.
        /// </summary>
        public static string ArenaOfValour {
            get {
                return ResourceManager.GetString("ArenaOfValour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armourer&apos;s Workshop.
        /// </summary>
        public static string ArmourersWorkshop {
            get {
                return ResourceManager.GetString("ArmourersWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Armour
        ///Animate Guardian Recipe.
        /// </summary>
        public static string ArmourersWorkshopContains {
            get {
                return ResourceManager.GetString("ArmourersWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/20/30 &amp; more Monster Life.
        /// </summary>
        public static string ArmourersWorkshopModifiers {
            get {
                return ResourceManager.GetString("ArmourersWorkshopModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoury.
        /// </summary>
        public static string Armoury {
            get {
                return ResourceManager.GetString("Armoury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlas of Worlds.
        /// </summary>
        public static string AtlasOfWorlds {
            get {
                return ResourceManager.GetString("AtlasOfWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaton Lab.
        /// </summary>
        public static string AutomatonLab {
            get {
                return ResourceManager.GetString("AutomatonLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string Barracks {
            get {
                return ResourceManager.GetString("Barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breach Containment Chamber.
        /// </summary>
        public static string BreachContainmentChamber {
            get {
                return ResourceManager.GetString("BreachContainmentChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalyst of Corruption.
        /// </summary>
        public static string CatalystOfCorruption {
            get {
                return ResourceManager.GetString("CatalystOfCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber of Iron.
        /// </summary>
        public static string ChamberOfIron {
            get {
                return ResourceManager.GetString("ChamberOfIron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix: 
        ///Minions deal 90-138% increased Damage
        ///------------------------------------
        ///+2 to Level of socketed Minion Gems
        ///------------------------------------
        ///Minions deal 70-110% increased Damage
        ///Minions have 5% Chance to deal Double Damage
        ///------------------------------------
        ///Suffix: 
        ///Minions have 13-40% increased Attack Speed
        ///Minions have 13-40% increased Cast Speed
        ///------------------------------------
        ///17-30% increased Minion Duration.
        /// </summary>
        public static string CitaqualotlModTooltip {
            get {
                return ResourceManager.GetString("CitaqualotlModTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conduit of Lightning.
        /// </summary>
        public static string ConduitOfLightning {
            get {
                return ResourceManager.GetString("ConduitOfLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corruption Chamber.
        /// </summary>
        public static string CorruptionChamber {
            get {
                return ResourceManager.GetString("CorruptionChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Double Corruption.
        /// </summary>
        public static string CorruptionChamberContains {
            get {
                return ResourceManager.GetString("CorruptionChamberContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6/8/10 % maximum Player Resistances.
        /// </summary>
        public static string CorruptionChamberModifiers {
            get {
                return ResourceManager.GetString("CorruptionChamberModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court of Sealed Death.
        /// </summary>
        public static string CourtOfTheSealedDeath {
            get {
                return ResourceManager.GetString("CourtOfTheSealedDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crucible of Flame.
        /// </summary>
        public static string CrucibleOfFlame {
            get {
                return ResourceManager.GetString("CrucibleOfFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivar Chamber.
        /// </summary>
        public static string CultivarChamber {
            get {
                return ResourceManager.GetString("CultivarChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Research Lab.
        /// </summary>
        public static string DefenseResearchLab {
            get {
                return ResourceManager.GetString("DefenseResearchLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demolition Lab.
        /// </summary>
        public static string DemolitionLab {
            get {
                return ResourceManager.GetString("DemolitionLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Thaumaturgy.
        /// </summary>
        public static string DepartmentOfThaumaturgy {
            get {
                return ResourceManager.GetString("DepartmentOfThaumaturgy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doryani&apos;s Institute.
        /// </summary>
        public static string DoryanisInstitute {
            get {
                return ResourceManager.GetString("DoryanisInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible outcomes: 
        ///Change all sockets to white 
        ///Add two imnplicit Vaal modifiers 
        ///Transform Sacrifical Garb into Shadowstitch 
        ///Transform into a rare Item with random influence 
        ///Destroy the item.
        /// </summary>
        public static string DoubleCorruptionTooltip {
            get {
                return ResourceManager.GetString("DoubleCorruptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to corruptions to a Gem
        ///Possible to get a 21/23 Gem.
        /// </summary>
        public static string DoubleGemCorruptionTooltip {
            get {
                return ResourceManager.GetString("DoubleGemCorruptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Department.
        /// </summary>
        public static string EngineeringDepartment {
            get {
                return ResourceManager.GetString("EngineeringDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosives Room.
        /// </summary>
        public static string ExplosivesRoom {
            get {
                return ResourceManager.GetString("ExplosivesRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2/3 Explosive Kegs
        ///[Used to unlock doors].
        /// </summary>
        public static string ExplosivesRoomContains {
            get {
                return ResourceManager.GetString("ExplosivesRoomContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flame Workshop.
        /// </summary>
        public static string FlameWorkshop {
            get {
                return ResourceManager.GetString("FlameWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Puhuarte Mod or Story of the Vaal.
        /// </summary>
        public static string FlameWorkshopContains {
            get {
                return ResourceManager.GetString("FlameWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augments the Omnitect with fire.
        /// </summary>
        public static string FlameWorkshopModifiers {
            get {
                return ResourceManager.GetString("FlameWorkshopModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemcutter&apos;s Workshop.
        /// </summary>
        public static string GemcuttersWorkshop {
            get {
                return ResourceManager.GetString("GemcuttersWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Gems
        ///Level 3: Double Gem Corruption.
        /// </summary>
        public static string GemcuttersWorkshopContains {
            get {
                return ResourceManager.GetString("GemcuttersWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glittering Halls.
        /// </summary>
        public static string GlitteringHalls {
            get {
                return ResourceManager.GetString("GlitteringHalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardhouse.
        /// </summary>
        public static string Guardhouse {
            get {
                return ResourceManager.GetString("Guardhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +10/20/30 % Monster Pack Size.
        /// </summary>
        public static string GuardhouseModifiers {
            get {
                return ResourceManager.GetString("GuardhouseModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix: 
        ///+70-119 to Maximum Life
        ///3-10% increased Maximum Life
        ///--------------------------------
        ///+44-47 to Maximum Energy Shield
        ///7-10% increased Maximum Energy Shield
        ///--------------------------------
        ///+44-47 to Maximum Energy Shield
        ///Regenerate 0.4% of Energy Shield per Second
        ///--------------------------------
        ///Suffix: 
        ///Regenerate 16-20 Life per Second
        ///Regenerate 0.4% of Life per Second.
        /// </summary>
        public static string GuateliztzModTooltip {
            get {
                return ResourceManager.GetString("GuateliztzModTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Champions.
        /// </summary>
        public static string HallOfChampions {
            get {
                return ResourceManager.GetString("HallOfChampions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Heroes.
        /// </summary>
        public static string HallOfHeroes {
            get {
                return ResourceManager.GetString("HallOfHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Legends.
        /// </summary>
        public static string HallOfLegends {
            get {
                return ResourceManager.GetString("HallOfLegends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Locks.
        /// </summary>
        public static string HallOfLocks {
            get {
                return ResourceManager.GetString("HallOfLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Lords.
        /// </summary>
        public static string HallOfLords {
            get {
                return ResourceManager.GetString("HallOfLords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Mettle.
        /// </summary>
        public static string HallOfMettle {
            get {
                return ResourceManager.GetString("HallOfMettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1: Timeless Monolith
        ///Level 2: Guaranteed War Hoard
        ///Level 3: Guaranteed General.
        /// </summary>
        public static string HallOfMettleContains {
            get {
                return ResourceManager.GetString("HallOfMettleContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Offerings.
        /// </summary>
        public static string HallOfOfferings {
            get {
                return ResourceManager.GetString("HallOfOfferings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of War.
        /// </summary>
        public static string HallOfWar {
            get {
                return ResourceManager.GetString("HallOfWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchery.
        /// </summary>
        public static string Hatchery {
            get {
                return ResourceManager.GetString("Hatchery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Citaqualotl Mod or Coward&apos;s Chains.
        /// </summary>
        public static string HatcheryContains {
            get {
                return ResourceManager.GetString("HatcheryContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augments the Omnitect with minions.
        /// </summary>
        public static string HatcheryModifiers {
            get {
                return ResourceManager.GetString("HatcheryModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string HeaderContains {
            get {
                return ResourceManager.GetString("HeaderContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string HeaderModifiers {
            get {
                return ResourceManager.GetString("HeaderModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House of the Others.
        /// </summary>
        public static string HouseOfOthers {
            get {
                return ResourceManager.GetString("HouseOfOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurricane Engine.
        /// </summary>
        public static string HurricaneEngine {
            get {
                return ResourceManager.GetString("HurricaneEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybridisation Chamber.
        /// </summary>
        public static string HybridisationChamber {
            get {
                return ResourceManager.GetString("HybridisationChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweller&apos;s Workshop.
        /// </summary>
        public static string JewellersWorkshop {
            get {
                return ResourceManager.GetString("JewellersWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewellery, Talismans, Div Cards.
        /// </summary>
        public static string JewellersWorkshopContains {
            get {
                return ResourceManager.GetString("JewellersWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewellery Forge.
        /// </summary>
        public static string JewelleryForge {
            get {
                return ResourceManager.GetString("JewelleryForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning Workshop.
        /// </summary>
        public static string LightningWorkshop {
            get {
                return ResourceManager.GetString("LightningWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Xopec Mod or Dance o fthe Offered.
        /// </summary>
        public static string LightningWorkshopContains {
            get {
                return ResourceManager.GetString("LightningWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augments the Omnitect with lightning.
        /// </summary>
        public static string LightningWorkshopModifiers {
            get {
                return ResourceManager.GetString("LightningWorkshopModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locus of Corruption.
        /// </summary>
        public static string LocuOfCorruption {
            get {
                return ResourceManager.GetString("LocuOfCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix: 
        ///30% increased Movement Speed
        ///5-6% chance to Dodge Spell Hits
        ///--------------------------------------
        ///90-138% increased Trap/Mine Damage
        ///--------------------------------------
        ///+2 to Level of socketed Trap/Trap or Mine Gems
        ///--------------------------------------
        ///Suffix: 
        ///20-33% increased Trap/Mine Throwing Speed
        ///--------------------------------------
        ///14-22% increased Cooldown Recovery Speed for Throwing Traps
        ///17-30% increased Trap Duration
        ///--------------------------------------
        ///Mines hav [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MatalTooltip {
            get {
                return ResourceManager.GetString("MatalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum of Artifacts.
        /// </summary>
        public static string MuseumOfArtifacts {
            get {
                return ResourceManager.GetString("MuseumOfArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of Cartography.
        /// </summary>
        public static string OfficeOfCartography {
            get {
                return ResourceManager.GetString("OfficeOfCartography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnitect Forge.
        /// </summary>
        public static string OmnitectForge {
            get {
                return ResourceManager.GetString("OmnitectForge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnitect Reactor Plant.
        /// </summary>
        public static string OmnitectReactorPlant {
            get {
                return ResourceManager.GetString("OmnitectReactorPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Garden.
        /// </summary>
        public static string PoisionGarden {
            get {
                return ResourceManager.GetString("PoisionGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Caustic Ground Plants.
        /// </summary>
        public static string PoisonGardenModifiers {
            get {
                return ResourceManager.GetString("PoisonGardenModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pools of Restoration.
        /// </summary>
        public static string PoolsOfRestoration {
            get {
                return ResourceManager.GetString("PoolsOfRestoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leech Rank 2 Recipe
        ///Level 3: Guatelitzi Mod or Mask of the Spirit Drinker.
        /// </summary>
        public static string PoolsOfRestorationContains {
            get {
                return ResourceManager.GetString("PoolsOfRestorationContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster regenerate 4/6/8 % Life per Second.
        /// </summary>
        public static string PoolsOfRestorationModifiers {
            get {
                return ResourceManager.GetString("PoolsOfRestorationModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Damage Rank 3 Recipe
        ///Level 3: Tacati Mod or Apep&apos;s Slumber.
        /// </summary>
        public static string PosionGardenContains {
            get {
                return ResourceManager.GetString("PosionGardenContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix: 
        ///+46-48% to Fire/Cold/Lightning Resistance
        ///9-10% of Physical Damage from Hits taken as Fire/Cold/Lightning Damage
        ///------------------------------------------
        ///+46-48% to Fire/Cold/Lightning Resistance
        ///0.4% of Fire/Cold/Lightning Damage leeched as Life
        ///------------------------------------------
        ///+46-48% to Fire/Cold/Lightning Resistance
        ///On of the following matching the Resistance:
        ///(45-52) to (75-78) added Fire Damage against Burning Enemies
        ///(30-50)% increased Damage with Hits against Chilled E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PuhuarteModTooltuip {
            get {
                return ResourceManager.GetString("PuhuarteModTooltuip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Meeting Room.
        /// </summary>
        public static string RoyalMeetingRoom {
            get {
                return ResourceManager.GetString("RoyalMeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Atziri Boss.
        /// </summary>
        public static string RoyalMeetingRoomContains {
            get {
                return ResourceManager.GetString("RoyalMeetingRoomContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/15/20 % increased Attack/Cast Speed.
        /// </summary>
        public static string RoyalMeetingRoomModifiers {
            get {
                return ResourceManager.GetString("RoyalMeetingRoomModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1: Change Unique to other
        ///Level 2: Can obtain League Specific Items
        ///Level 3: Unique Item of same class/Vial Upgrade.
        /// </summary>
        public static string SacrificalChamberContains {
            get {
                return ResourceManager.GetString("SacrificalChamberContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacrificial Chamber.
        /// </summary>
        public static string SacrificialChamber {
            get {
                return ResourceManager.GetString("SacrificialChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadist&apos;s Den.
        /// </summary>
        public static string SadistsDen {
            get {
                return ResourceManager.GetString("SadistsDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctum of Immortality.
        /// </summary>
        public static string SanctumOfImmortality {
            get {
                return ResourceManager.GetString("SanctumOfImmortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctum of Unity.
        /// </summary>
        public static string SanctumOfUnity {
            get {
                return ResourceManager.GetString("SanctumOfUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctum of Vitality.
        /// </summary>
        public static string SanctumOfVitality {
            get {
                return ResourceManager.GetString("SanctumOfVitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrine of Empowerment.
        /// </summary>
        public static string ShrineOfEmpowerment {
            get {
                return ResourceManager.GetString("ShrineOfEmpowerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Upgrade connected rooms by 1 tier.
        /// </summary>
        public static string ShrineOfEmpowermentContains {
            get {
                return ResourceManager.GetString("ShrineOfEmpowermentContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/15/20 % increased Attack/Cast Speed.
        /// </summary>
        public static string ShrineOfEmpowermentModifiers {
            get {
                return ResourceManager.GetString("ShrineOfEmpowermentModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrine of Unmaking.
        /// </summary>
        public static string ShrineOfUnmaking {
            get {
                return ResourceManager.GetString("ShrineOfUnmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparring Room.
        /// </summary>
        public static string SparringRoom {
            get {
                return ResourceManager.GetString("SparringRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Weapons
        ///Accuracy Rank 3 Recipe.
        /// </summary>
        public static string SparringRoomContains {
            get {
                return ResourceManager.GetString("SparringRoomContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/15/20 % increased Monster Damage.
        /// </summary>
        public static string SparringRoomModifiers {
            get {
                return ResourceManager.GetString("SparringRoomModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splinter Research Lab.
        /// </summary>
        public static string SplinterResearchLab {
            get {
                return ResourceManager.GetString("SplinterResearchLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1: 2 Clasped Hands
        ///Level 2: 1 Breach
        ///Level 3: 3 Breaches.
        /// </summary>
        public static string SplinterResearchLabContains {
            get {
                return ResourceManager.GetString("SplinterResearchLabContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Room.
        /// </summary>
        public static string StorageRoom {
            get {
                return ResourceManager.GetString("StorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Item-Specific Chests
        ///Level 3: League Specific Items possible.
        /// </summary>
        public static string StorageRoomContains {
            get {
                return ResourceManager.GetString("StorageRoomContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm of Corruption.
        /// </summary>
        public static string StormOfCorruption {
            get {
                return ResourceManager.GetString("StormOfCorruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongbox Chamber.
        /// </summary>
        public static string StrongboxChamber {
            get {
                return ResourceManager.GetString("StrongboxChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room contains 2/4/6 Strongboxes.
        /// </summary>
        public static string StrongboxChamberContains {
            get {
                return ResourceManager.GetString("StrongboxChamberContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor&apos;s Study.
        /// </summary>
        public static string SurveyorsStudy {
            get {
                return ResourceManager.GetString("SurveyorsStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps (possible Vaal Prefix).
        /// </summary>
        public static string SurveyorsStudyContains {
            get {
                return ResourceManager.GetString("SurveyorsStudyContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix: 
        ///155-169% increased Physical Damage+
        ///Gain 9-10% of Physical Damage as Extra Chaos Damage
        ///--------------------------------------------------------
        ///70-110% increased Spell Damage
        ///Gain 5% of Non-Chaos Damage as Extra Chaos Damage
        ///--------------------------------------------------------
        ///Suffix: 
        ///23-38% increased Cast Speed
        ///Adds 17-57 Chaos Damage to Spells
        ///--------------------------------------------------------
        ///14-27% increased Attack Speed
        ///Adds 23-61 Chaos Damage
        ///------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TacatiModTooltip {
            get {
                return ResourceManager.GetString("TacatiModTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempest Generator.
        /// </summary>
        public static string TempestGenerator {
            get {
                return ResourceManager.GetString("TempestGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3: Topolante Mod.
        /// </summary>
        public static string TempestGeneratorContains {
            get {
                return ResourceManager.GetString("TempestGeneratorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Tempests.
        /// </summary>
        public static string TempestGeneratorModifiers {
            get {
                return ResourceManager.GetString("TempestGeneratorModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temple Defense Workshop.
        /// </summary>
        public static string TempleDefenseWorkshop {
            get {
                return ResourceManager.GetString("TempleDefenseWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temple Nexus.
        /// </summary>
        public static string TempleNexus {
            get {
                return ResourceManager.GetString("TempleNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throne of Atziri.
        /// </summary>
        public static string ThroneOfAtziri {
            get {
                return ResourceManager.GetString("ThroneOfAtziri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Prefixes: 
        ///Add Fire/Cold/Lightning Damage to Attacks
        ///25% of Physical Damage Converted to Fire/Cold/Lighning Damage
        ///---------------------------------------------------------------------
        ///Add Fire/Cold/Lightning Damage 
        ///Damage Penetrates 13-15% Fire/Cold/Lightning Resistance 
        ///---------------------------------------------------------------------
        ///75-115% increased Fire/Cold/Lightning Damage 
        ///Add Fire/Cold/Lightning Damage to Spells.
        /// </summary>
        public static string TopotanteModTooltip {
            get {
                return ResourceManager.GetString("TopotanteModTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torment Cells.
        /// </summary>
        public static string TormentCells {
            get {
                return ResourceManager.GetString("TormentCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room contains 3/5/7 Tormented Spirits.
        /// </summary>
        public static string TormentCellsContains {
            get {
                return ResourceManager.GetString("TormentCellsContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torture Cages.
        /// </summary>
        public static string TortureCages {
            get {
                return ResourceManager.GetString("TortureCages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxic Grove.
        /// </summary>
        public static string ToxicGrove {
            get {
                return ResourceManager.GetString("ToxicGrove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap Workshop.
        /// </summary>
        public static string TrapWorkshop {
            get {
                return ResourceManager.GetString("TrapWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps and Mines Rank 2 Recipe
        ///Level 3: Matatl Mod or Architect&apos;s Hand.
        /// </summary>
        public static string TrapWorkshopContains {
            get {
                return ResourceManager.GetString("TrapWorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Labyrinth Traps.
        /// </summary>
        public static string TrapWorkshopModifiers {
            get {
                return ResourceManager.GetString("TrapWorkshopModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasury.
        /// </summary>
        public static string Treasury {
            get {
                return ResourceManager.GetString("Treasury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault.
        /// </summary>
        public static string Vault {
            get {
                return ResourceManager.GetString("Vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Items inckuding Stacks and Shards.
        /// </summary>
        public static string VaultContains {
            get {
                return ResourceManager.GetString("VaultContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wealth of the Vaal.
        /// </summary>
        public static string WealthOfTheVaal {
            get {
                return ResourceManager.GetString("WealthOfTheVaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticals Rank 3 Recipe.
        /// </summary>
        public static string WorkshopContains {
            get {
                return ResourceManager.GetString("WorkshopContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5/10/15 % increased Quantity of Items
        ///Unique Boss has 15/25/35 % increased Life.
        /// </summary>
        public static string WorkshopModifiers {
            get {
                return ResourceManager.GetString("WorkshopModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix: 
        ///+69-73 to maximum Mana
        ///7-10% increased maximum Mana
        ///--------------------------------
        ///+74-78 to maximum Mana
        ///+2-3 Mana gained for each Enemy hit by your Attacks
        ///--------------------------------
        ///+74-78 to maximum Mana
        ///Regenerate 5-7 Mana per Second
        ///--------------------------------
        ///+69-73 to maximum Mana
        ///3-5% reduced Mana Reserved
        ///--------------------------------
        ///+74-78 to maximum Mana
        ///-6-8 to Total Mana Cost of Skills
        ///--------------------------------
        ///+74-78 to maximum Mana
        ///Non-Channe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XopecModTooltip {
            get {
                return ResourceManager.GetString("XopecModTooltip", resourceCulture);
            }
        }
    }
}
