//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Metamorph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetamorphResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetamorphResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Metamorph.MetamorphResources", typeof(MetamorphResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrasive Catalyst.
        /// </summary>
        public static string AbrasiveCatalyst {
            get {
                return ResourceManager.GetString("AbrasiveCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quality that enchances
        ///Attack modifiers.
        /// </summary>
        public static string AbrasiveCatalystEffect {
            get {
                return ResourceManager.GetString("AbrasiveCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertile Catalyst.
        /// </summary>
        public static string FertileCatalyst {
            get {
                return ResourceManager.GetString("FertileCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quality that enhances
        ///Life and Mana Modifiers.
        /// </summary>
        public static string FertileCatalystEffect {
            get {
                return ResourceManager.GetString("FertileCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imbued Catalyst.
        /// </summary>
        public static string ImbuedCatalyst {
            get {
                return ResourceManager.GetString("ImbuedCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quality that enhances
        ///Caster Modifiers.
        /// </summary>
        public static string ImbuedCatalystEffect {
            get {
                return ResourceManager.GetString("ImbuedCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationHeader {
            get {
                return ResourceManager.GetString("InformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be applied to: 
        ///Rings, Amulets, Belts 
        ///Applying a Catalyst removes all other Quality.
        /// </summary>
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrinsic Catalyst.
        /// </summary>
        public static string IntrinsicCatalyst {
            get {
                return ResourceManager.GetString("IntrinsicCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Quality that enhances
        ///Attribute Modifiers.
        /// </summary>
        public static string IntrinsicCatalystEffect {
            get {
                return ResourceManager.GetString("IntrinsicCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prismatic Catalyst.
        /// </summary>
        public static string PrismaticCatalyst {
            get {
                return ResourceManager.GetString("PrismaticCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Quality that enhances
        ///Resistance Modifiers.
        /// </summary>
        public static string PrismaticCatalystEffect {
            get {
                return ResourceManager.GetString("PrismaticCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempering Catalyst.
        /// </summary>
        public static string TemperingCatalyst {
            get {
                return ResourceManager.GetString("TemperingCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quality that enhances
        ///Defense Modifiers.
        /// </summary>
        public static string TemperingCatalystEffect {
            get {
                return ResourceManager.GetString("TemperingCatalystEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbulent Catalyst.
        /// </summary>
        public static string TurbulentCatalyst {
            get {
                return ResourceManager.GetString("TurbulentCatalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Quality that enhances
        ///Elemental Damage Modifiers.
        /// </summary>
        public static string TurbulentCatalystEffect {
            get {
                return ResourceManager.GetString("TurbulentCatalystEffect", resourceCulture);
            }
        }
    }
}
