//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Presentation.Localization.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Presentation.Localization.Settings.SettingResources", typeof(SettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        public static string Character_League {
            get {
                return ResourceManager.GetString("Character_League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string Character_Name {
            get {
                return ResourceManager.GetString("Character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Settings.
        /// </summary>
        public static string Character_Title {
            get {
                return ResourceManager.GetString("Character_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Commands.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Character Selection.
        /// </summary>
        public static string Chat_Key_Exit {
            get {
                return ResourceManager.GetString("Chat_Key_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Hideout.
        /// </summary>
        public static string Chat_Key_Hideout {
            get {
                return ResourceManager.GetString("Chat_Key_Hideout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Party.
        /// </summary>
        public static string Chat_Key_LeaveParty {
            get {
                return ResourceManager.GetString("Chat_Key_LeaveParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheatsheets.
        /// </summary>
        public static string Cheatsheets {
            get {
                return ResourceManager.GetString("Cheatsheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cheatsheets.
        /// </summary>
        public static string Cheatsheets_Key_Open {
            get {
                return ResourceManager.GetString("Cheatsheets_Key_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Clipboard Data.
        /// </summary>
        public static string General_RetainClipboard {
            get {
                return ResourceManager.GetString("General_RetainClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the splash screen when starting.
        /// </summary>
        public static string General_ShowSplashScreen {
            get {
                return ResourceManager.GetString("General_ShowSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybindings.
        /// </summary>
        public static string Group_Keybinds {
            get {
                return ResourceManager.GetString("Group_Keybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string Group_Other {
            get {
                return ResourceManager.GetString("Group_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Items.
        /// </summary>
        public static string Key_FindItems {
            get {
                return ResourceManager.GetString("Key_FindItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings View.
        /// </summary>
        public static string Key_OpenSettings {
            get {
                return ResourceManager.GetString("Key_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Language.
        /// </summary>
        public static string Language_Parser {
            get {
                return ResourceManager.GetString("Language_Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        public static string Language_UI {
            get {
                return ResourceManager.GetString("Language_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Information.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Modifiers.
        /// </summary>
        public static string Map_Dangerous {
            get {
                return ResourceManager.GetString("Map_Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Map_Dangerous_Regex {
            get {
                return ResourceManager.GetString("Map_Dangerous_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Map Mods.
        /// </summary>
        public static string Map_Key_Check {
            get {
                return ResourceManager.GetString("Map_Key_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Overlay with Mouse Click.
        /// </summary>
        public static string Overlay_CloseWithMouse {
            get {
                return ResourceManager.GetString("Overlay_CloseWithMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string Overlay_Key_Close {
            get {
                return ResourceManager.GetString("Overlay_Key_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Information.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Prices.
        /// </summary>
        public static string Price_Key_Check {
            get {
                return ResourceManager.GetString("Price_Key_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Search.
        /// </summary>
        public static string Price_Key_OpenSearch {
            get {
                return ResourceManager.GetString("Price_Key_OpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Price Prediction.
        /// </summary>
        public static string Price_Prediction_Enable {
            get {
                return ResourceManager.GetString("Price_Prediction_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Cache.
        /// </summary>
        public static string ResetCache {
            get {
                return ResourceManager.GetString("ResetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash Commands.
        /// </summary>
        public static string Stash {
            get {
                return ResourceManager.GetString("Stash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tab Scrolling with Ctrl + Scroll.
        /// </summary>
        public static string Stash_EnableCtrlScroll {
            get {
                return ResourceManager.GetString("Stash_EnableCtrlScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Scroll Left.
        /// </summary>
        public static string Stash_Key_Left {
            get {
                return ResourceManager.GetString("Stash_Key_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Scroll Right.
        /// </summary>
        public static string Stash_Key_Right {
            get {
                return ResourceManager.GetString("Stash_Key_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Settings.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wiki.
        /// </summary>
        public static string Wiki_Key_Open {
            get {
                return ResourceManager.GetString("Wiki_Key_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Wiki.
        /// </summary>
        public static string Wiki_Preferred {
            get {
                return ResourceManager.GetString("Wiki_Preferred", resourceCulture);
            }
        }
    }
}
