//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Settings.SettingResources", typeof(SettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string Character_Name {
            get {
                return ResourceManager.GetString("Character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Settings.
        /// </summary>
        public static string Character_Title {
            get {
                return ResourceManager.GetString("Character_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Prices.
        /// </summary>
        public static string Key_CheckPrices {
            get {
                return ResourceManager.GetString("Key_CheckPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string Key_CloseWindow {
            get {
                return ResourceManager.GetString("Key_CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Items.
        /// </summary>
        public static string Key_FindItems {
            get {
                return ResourceManager.GetString("Key_FindItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Hideout.
        /// </summary>
        public static string Key_GoToHideout {
            get {
                return ResourceManager.GetString("Key_GoToHideout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Party.
        /// </summary>
        public static string Key_LeaveParty {
            get {
                return ResourceManager.GetString("Key_LeaveParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open League Overview.
        /// </summary>
        public static string Key_OpenLeagueOverview {
            get {
                return ResourceManager.GetString("Key_OpenLeagueOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Search.
        /// </summary>
        public static string Key_OpenSearch {
            get {
                return ResourceManager.GetString("Key_OpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wiki.
        /// </summary>
        public static string Key_OpenWiki {
            get {
                return ResourceManager.GetString("Key_OpenWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        public static string Language_UI {
            get {
                return ResourceManager.GetString("Language_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Overlay with Mouse Click.
        /// </summary>
        public static string Other_CloseWithMouseClick {
            get {
                return ResourceManager.GetString("Other_CloseWithMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Clipboard Data.
        /// </summary>
        public static string Other_RetainClipboard {
            get {
                return ResourceManager.GetString("Other_RetainClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tab Scrolling with Ctrl + Scroll.
        /// </summary>
        public static string Other_TabScroll {
            get {
                return ResourceManager.GetString("Other_TabScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string Other_Title {
            get {
                return ResourceManager.GetString("Other_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_General {
            get {
                return ResourceManager.GetString("Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybindings.
        /// </summary>
        public static string Tab_Keybindings {
            get {
                return ResourceManager.GetString("Tab_Keybindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Wiki.
        /// </summary>
        public static string Wiki_Preferred {
            get {
                return ResourceManager.GetString("Wiki_Preferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Settings.
        /// </summary>
        public static string Wiki_Title {
            get {
                return ResourceManager.GetString("Wiki_Title", resourceCulture);
            }
        }
    }
}
