//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Splash {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SplashResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SplashResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Splash.SplashResources", typeof(SplashResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of Sidekick is already running.
        /// </summary>
        public static string AlreadyRunningText {
            get {
                return ResourceManager.GetString("AlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sideckick is already running.
        /// </summary>
        public static string AlreadyRunningTitle {
            get {
                return ResourceManager.GetString("AlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing (3 of 3).
        /// </summary>
        public static string Type_AfterInit {
            get {
                return ResourceManager.GetString("Type_AfterInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing (1 of 3).
        /// </summary>
        public static string Type_BeforeInit {
            get {
                return ResourceManager.GetString("Type_BeforeInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing (2 of 3).
        /// </summary>
        public static string Type_Init {
            get {
                return ResourceManager.GetString("Type_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Type_Other {
            get {
                return ResourceManager.GetString("Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinitializing.
        /// </summary>
        public static string Type_Reset {
            get {
                return ResourceManager.GetString("Type_Reset", resourceCulture);
            }
        }
    }
}
