//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Prices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PriceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Prices.PriceResources", typeof(PriceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string Age_Day {
            get {
                return ResourceManager.GetString("Age_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string Age_Days {
            get {
                return ResourceManager.GetString("Age_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string Age_Hour {
            get {
                return ResourceManager.GetString("Age_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string Age_Hours {
            get {
                return ResourceManager.GetString("Age_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string Age_Minute {
            get {
                return ResourceManager.GetString("Age_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string Age_Minutes {
            get {
                return ResourceManager.GetString("Age_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Age_Now {
            get {
                return ResourceManager.GetString("Age_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string Age_Seconds {
            get {
                return ResourceManager.GetString("Age_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted.
        /// </summary>
        public static string Corrupted {
            get {
                return ResourceManager.GetString("Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} out of {1} items.
        /// </summary>
        public static string CountString {
            get {
                return ResourceManager.GetString("CountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find prices for this item..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage per second.
        /// </summary>
        public static string Filters_Dps {
            get {
                return ResourceManager.GetString("Filters_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental DPS.
        /// </summary>
        public static string Filters_EDps {
            get {
                return ResourceManager.GetString("Filters_EDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Filters_Max {
            get {
                return ResourceManager.GetString("Filters_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Filters_Min {
            get {
                return ResourceManager.GetString("Filters_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPS.
        /// </summary>
        public static string Filters_PDps {
            get {
                return ResourceManager.GetString("Filters_PDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        public static string ItemLevel {
            get {
                return ResourceManager.GetString("ItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More Data.
        /// </summary>
        public static string LoadMoreData {
            get {
                return ResourceManager.GetString("LoadMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour at max Quality.
        /// </summary>
        public static string MaxQualityArmour {
            get {
                return ResourceManager.GetString("MaxQualityArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS at max Quality.
        /// </summary>
        public static string MaxQualityDps {
            get {
                return ResourceManager.GetString("MaxQualityDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental DPS at max Quality.
        /// </summary>
        public static string MaxQualityEDps {
            get {
                return ResourceManager.GetString("MaxQualityEDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Shield at max Quality.
        /// </summary>
        public static string MaxQualityEnergyShield {
            get {
                return ResourceManager.GetString("MaxQualityEnergyShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion at max Quality.
        /// </summary>
        public static string MaxQualityEvasion {
            get {
                return ResourceManager.GetString("MaxQualityEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical DPS at max Quality.
        /// </summary>
        public static string MaxQualityPDps {
            get {
                return ResourceManager.GetString("MaxQualityPDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string OverlayAccountName {
            get {
                return ResourceManager.GetString("OverlayAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string OverlayAge {
            get {
                return ResourceManager.GetString("OverlayAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string OverlayCharacter {
            get {
                return ResourceManager.GetString("OverlayCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iLvl.
        /// </summary>
        public static string OverlayItemLevel {
            get {
                return ResourceManager.GetString("OverlayItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string OverlayPrice {
            get {
                return ResourceManager.GetString("OverlayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poe.Ninja: {0}c - Last updated: {1}.
        /// </summary>
        public static string PoeNinjaString {
            get {
                return ResourceManager.GetString("PoeNinjaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction: {0} - Confidence: {1}%.
        /// </summary>
        public static string PredictionString {
            get {
                return ResourceManager.GetString("PredictionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires.
        /// </summary>
        public static string Requires {
            get {
                return ResourceManager.GetString("Requires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified.
        /// </summary>
        public static string Unidentified {
            get {
                return ResourceManager.GetString("Unidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        public static string UpdateSeconds {
            get {
                return ResourceManager.GetString("UpdateSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating shortly.
        /// </summary>
        public static string UpdateShortly {
            get {
                return ResourceManager.GetString("UpdateShortly", resourceCulture);
            }
        }
    }
}
