namespace GregsStack.InputSimulatorStandard.Native
{
    /// <summary>
    /// The <see cref="HardwareInput"/> structure contains information about a simulated message generated by an input device other than a keyboard or mouse. (see: http://msdn.microsoft.com/en-us/library/ms646269(VS.85).aspx)
    /// Declared in Winuser.h, include Windows.h
    /// </summary>
    internal struct HardwareInput
    {
        /// <summary>
        /// Value specifying the message generated by the input hardware. 
        /// </summary>
        public uint Msg;

        /// <summary>
        /// Specifies the low-order word of the lParam parameter for uMsg. 
        /// </summary>
        public ushort ParamL;

        /// <summary>
        /// Specifies the high-order word of the lParam parameter for uMsg. 
        /// </summary>
        public ushort ParamH;
    }
}
