using Microsoft.Extensions.Localization;

namespace Sidekick.Localization.Cheatsheets
{
    public class IncursionResources
    {
        private readonly IStringLocalizer<IncursionResources> localizer;

        public IncursionResources(IStringLocalizer<IncursionResources> localizer)
        {
            this.localizer = localizer;
        }

        public string ApexOfAscension => localizer["ApexOfAscension"];
        public string ArenaOfValour => localizer["ArenaOfValour"];
        public string ArmourersWorkshop => localizer["ArmourersWorkshop"];
        public string ArmourersWorkshopContains => localizer["ArmourersWorkshopContains"];
        public string ArmourersWorkshopModifiers => localizer["ArmourersWorkshopModifiers"];
        public string Armoury => localizer["Armoury"];
        public string AtlasOfWorlds => localizer["AtlasOfWorlds"];
        public string AutomatonLab => localizer["AutomatonLab"];
        public string Barracks => localizer["Barracks"];
        public string BreachContainmentChamber => localizer["BreachContainmentChamber"];
        public string CatalystOfCorruption => localizer["CatalystOfCorruption"];
        public string ChamberOfIron => localizer["ChamberOfIron"];
        public string CitaqualotlModTooltip => localizer["CitaqualotlModTooltip"];
        public string ConduitOfLightning => localizer["ConduitOfLightning"];
        public string Contains => localizer["Contains"];
        public string CorruptionChamber => localizer["CorruptionChamber"];
        public string CorruptionChamberContains => localizer["CorruptionChamberContains"];
        public string CorruptionChamberModifiers => localizer["CorruptionChamberModifiers"];
        public string CourtOfTheSealedDeath => localizer["CourtOfTheSealedDeath"];
        public string CrucibleOfFlame => localizer["CrucibleOfFlame"];
        public string CultivarChamber => localizer["CultivarChamber"];
        public string DefenseResearchLab => localizer["DefenseResearchLab"];
        public string DemolitionLab => localizer["DemolitionLab"];
        public string DepartmentOfThaumaturgy => localizer["DepartmentOfThaumaturgy"];
        public string DoryanisInstitute => localizer["DoryanisInstitute"];
        public string DoubleCorruptionTooltip => localizer["DoubleCorruptionTooltip"];
        public string DoubleGemCorruptionTooltip => localizer["DoubleGemCorruptionTooltip"];
        public string EngineeringDepartment => localizer["EngineeringDepartment"];
        public string ExplosivesRoom => localizer["ExplosivesRoom"];
        public string ExplosivesRoomContains => localizer["ExplosivesRoomContains"];
        public string Factory => localizer["Factory"];
        public string FlameWorkshop => localizer["FlameWorkshop"];
        public string FlameWorkshopContains => localizer["FlameWorkshopContains"];
        public string FlameWorkshopModifiers => localizer["FlameWorkshopModifiers"];
        public string GemcuttersWorkshop => localizer["GemcuttersWorkshop"];
        public string GemcuttersWorkshopContains => localizer["GemcuttersWorkshopContains"];
        public string GlitteringHalls => localizer["GlitteringHalls"];
        public string Guardhouse => localizer["Guardhouse"];
        public string GuardhouseModifiers => localizer["GuardhouseModifiers"];
        public string GuateliztzModTooltip => localizer["GuateliztzModTooltip"];
        public string HallOfChampions => localizer["HallOfChampions"];
        public string HallOfHeroes => localizer["HallOfHeroes"];
        public string HallOfLegends => localizer["HallOfLegends"];
        public string HallOfLocks => localizer["HallOfLocks"];
        public string HallOfLords => localizer["HallOfLords"];
        public string HallOfMettle => localizer["HallOfMettle"];
        public string HallOfMettleContains => localizer["HallOfMettleContains"];
        public string HallOfOfferings => localizer["HallOfOfferings"];
        public string HallOfWar => localizer["HallOfWar"];
        public string Hatchery => localizer["Hatchery"];
        public string HatcheryContains => localizer["HatcheryContains"];
        public string HatcheryModifiers => localizer["HatcheryModifiers"];
        public string HeaderContains => localizer["HeaderContains"];
        public string HeaderModifiers => localizer["HeaderModifiers"];
        public string HouseOfOthers => localizer["HouseOfOthers"];
        public string HurricaneEngine => localizer["HurricaneEngine"];
        public string HybridisationChamber => localizer["HybridisationChamber"];
        public string JewellersWorkshop => localizer["JewellersWorkshop"];
        public string JewellersWorkshopContains => localizer["JewellersWorkshopContains"];
        public string JewelleryForge => localizer["JewelleryForge"];
        public string Legend => localizer["Legend"];
        public string Level1 => localizer["Level1"];
        public string Level2 => localizer["Level2"];
        public string Level3 => localizer["Level3"];
        public string LightningWorkshop => localizer["LightningWorkshop"];
        public string LightningWorkshopContains => localizer["LightningWorkshopContains"];
        public string LightningWorkshopModifiers => localizer["LightningWorkshopModifiers"];
        public string LocusOfCorruption => localizer["LocusOfCorruption"];
        public string MatalTooltip => localizer["MatalTooltip"];
        public string Modifiers => localizer["Modifiers"];
        public string MuseumOfArtifacts => localizer["MuseumOfArtifacts"];
        public string OfficeOfCartography => localizer["OfficeOfCartography"];
        public string OmnitectForge => localizer["OmnitectForge"];
        public string OmnitectReactorPlant => localizer["OmnitectReactorPlant"];
        public string PoisonGarden => localizer["PoisonGarden"];
        public string PoisonGardenContains => localizer["PoisonGardenContains"];
        public string PoisonGardenModifiers => localizer["PoisonGardenModifiers"];
        public string PoolsOfRestoration => localizer["PoolsOfRestoration"];
        public string PoolsOfRestorationContains => localizer["PoolsOfRestorationContains"];
        public string PoolsOfRestorationModifiers => localizer["PoolsOfRestorationModifiers"];
        public string PuhuarteModTooltuip => localizer["PuhuarteModTooltuip"];
        public string RoyalMeetingRoom => localizer["RoyalMeetingRoom"];
        public string RoyalMeetingRoomContains => localizer["RoyalMeetingRoomContains"];
        public string RoyalMeetingRoomModifiers => localizer["RoyalMeetingRoomModifiers"];
        public string SacrificalChamberContains => localizer["SacrificalChamberContains"];
        public string SacrificialChamber => localizer["SacrificialChamber"];
        public string SadistsDen => localizer["SadistsDen"];
        public string SanctumOfImmortality => localizer["SanctumOfImmortality"];
        public string SanctumOfUnity => localizer["SanctumOfUnity"];
        public string SanctumOfVitality => localizer["SanctumOfVitality"];
        public string ShrineOfEmpowerment => localizer["ShrineOfEmpowerment"];
        public string ShrineOfEmpowermentContains => localizer["ShrineOfEmpowermentContains"];
        public string ShrineOfEmpowermentModifiers => localizer["ShrineOfEmpowermentModifiers"];
        public string ShrineOfUnmaking => localizer["ShrineOfUnmaking"];
        public string SparringRoom => localizer["SparringRoom"];
        public string SparringRoomContains => localizer["SparringRoomContains"];
        public string SparringRoomModifiers => localizer["SparringRoomModifiers"];
        public string SplinterResearchLab => localizer["SplinterResearchLab"];
        public string SplinterResearchLabContains => localizer["SplinterResearchLabContains"];
        public string StorageRoom => localizer["StorageRoom"];
        public string StorageRoomContains => localizer["StorageRoomContains"];
        public string StormOfCorruption => localizer["StormOfCorruption"];
        public string StrongboxChamber => localizer["StrongboxChamber"];
        public string StrongboxChamberContains => localizer["StrongboxChamberContains"];
        public string SurveyorsStudy => localizer["SurveyorsStudy"];
        public string SurveyorsStudyContains => localizer["SurveyorsStudyContains"];
        public string TacatiModTooltip => localizer["TacatiModTooltip"];
        public string TempestGenerator => localizer["TempestGenerator"];
        public string TempestGeneratorContains => localizer["TempestGeneratorContains"];
        public string TempestGeneratorModifiers => localizer["TempestGeneratorModifiers"];
        public string TempleDefenseWorkshop => localizer["TempleDefenseWorkshop"];
        public string TempleNexus => localizer["TempleNexus"];
        public string ThroneOfAtziri => localizer["ThroneOfAtziri"];
        public string TopotanteModTooltip => localizer["TopotanteModTooltip"];
        public string TormentCells => localizer["TormentCells"];
        public string TormentCellsContains => localizer["TormentCellsContains"];
        public string TortureCages => localizer["TortureCages"];
        public string ToxicGrove => localizer["ToxicGrove"];
        public string TrapWorkshop => localizer["TrapWorkshop"];
        public string TrapWorkshopContains => localizer["TrapWorkshopContains"];
        public string TrapWorkshopModifiers => localizer["TrapWorkshopModifiers"];
        public string Treasury => localizer["Treasury"];
        public string Vault => localizer["Vault"];
        public string VaultContains => localizer["VaultContains"];
        public string Warehouses => localizer["Warehouses"];
        public string WealthOfTheVaal => localizer["WealthOfTheVaal"];
        public string Workshop => localizer["Workshop"];
        public string WorkshopContains => localizer["WorkshopContains"];
        public string WorkshopModifiers => localizer["WorkshopModifiers"];
        public string XopecModTooltip => localizer["XopecModTooltip"];
    }
}
