//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Localization.Leagues.Delve {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DelveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DelveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Localization.Leagues.Delve.DelveResources", typeof(DelveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abberant Fossil.
        /// </summary>
        public static string AberrantFossil {
            get {
                return ResourceManager.GetString("AberrantFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abyssal Depths.
        /// </summary>
        public static string AbyssalDepths {
            get {
                return ResourceManager.GetString("AbyssalDepths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetheric Fossil.
        /// </summary>
        public static string AethericFossil {
            get {
                return ResourceManager.GetString("AethericFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodstained Fossil.
        /// </summary>
        public static string BloodstainedFossil {
            get {
                return ResourceManager.GetString("BloodstainedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound Fossil.
        /// </summary>
        public static string BoundFossil {
            get {
                return ResourceManager.GetString("BoundFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corroded Fossil.
        /// </summary>
        public static string CorrodedFossil {
            get {
                return ResourceManager.GetString("CorrodedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dense Fossil.
        /// </summary>
        public static string DenseFossil {
            get {
                return ResourceManager.GetString("DenseFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted Fossil.
        /// </summary>
        public static string EnchantedFossil {
            get {
                return ResourceManager.GetString("EnchantedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrusted Fossil.
        /// </summary>
        public static string EncrustedFossil {
            get {
                return ResourceManager.GetString("EncrustedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faceted Fossil.
        /// </summary>
        public static string FacetedFossil {
            get {
                return ResourceManager.GetString("FacetedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fossil Room.
        /// </summary>
        public static string FossilRoom {
            get {
                return ResourceManager.GetString("FossilRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractured Fossil.
        /// </summary>
        public static string FracturedFossil {
            get {
                return ResourceManager.GetString("FracturedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigid Fossil.
        /// </summary>
        public static string FrigidFossil {
            get {
                return ResourceManager.GetString("FrigidFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen Hollow.
        /// </summary>
        public static string FrozenHollow {
            get {
                return ResourceManager.GetString("FrozenHollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fungal Caverns.
        /// </summary>
        public static string FungalCaverns {
            get {
                return ResourceManager.GetString("FungalCaverns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gilded Fossil.
        /// </summary>
        public static string GildedFossil {
            get {
                return ResourceManager.GetString("GildedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyphic Fossil.
        /// </summary>
        public static string GlyphicFossil {
            get {
                return ResourceManager.GetString("GlyphicFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Fossil.
        /// </summary>
        public static string HollowFossil {
            get {
                return ResourceManager.GetString("HollowFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Can only be found behind fractured walls.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jagged Fossil.
        /// </summary>
        public static string JaggedFossil {
            get {
                return ResourceManager.GetString("JaggedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucent Fossil.
        /// </summary>
        public static string LucentFossil {
            get {
                return ResourceManager.GetString("LucentFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magma Fissure.
        /// </summary>
        public static string MagmaFissure {
            get {
                return ResourceManager.GetString("MagmaFissure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metallic Fossil.
        /// </summary>
        public static string MetallicFossil {
            get {
                return ResourceManager.GetString("MetallicFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mines.
        /// </summary>
        public static string Mines {
            get {
                return ResourceManager.GetString("Mines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Fossil.
        /// </summary>
        public static string PerfectFossil {
            get {
                return ResourceManager.GetString("PerfectFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrified Forest.
        /// </summary>
        public static string PetrifiedForest {
            get {
                return ResourceManager.GetString("PetrifiedForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prismatic Fossil.
        /// </summary>
        public static string PrismaticFossil {
            get {
                return ResourceManager.GetString("PrismaticFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristine Fossil.
        /// </summary>
        public static string PristineFossil {
            get {
                return ResourceManager.GetString("PristineFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctified Fossil.
        /// </summary>
        public static string SanctifiedFossil {
            get {
                return ResourceManager.GetString("SanctifiedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorched Fossil.
        /// </summary>
        public static string ScorchedFossil {
            get {
                return ResourceManager.GetString("ScorchedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serrated Fossil.
        /// </summary>
        public static string SerratedFossil {
            get {
                return ResourceManager.GetString("SerratedFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuddering Fossil.
        /// </summary>
        public static string ShudderingFossil {
            get {
                return ResourceManager.GetString("ShudderingFossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfur Vents.
        /// </summary>
        public static string SulfurVents {
            get {
                return ResourceManager.GetString("SulfurVents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangled Fossil.
        /// </summary>
        public static string TangledFossil {
            get {
                return ResourceManager.GetString("TangledFossil", resourceCulture);
            }
        }
    }
}
